#!/usr/bin/env node
// Skill pack pricing RULE (decided 2026-09-02): a pack sells for the sum of the
// tools it advertises, minus a bundle discount, never below the settlement
// floor. One call, one payment, cheaper than assembling the steps yourself -
// the way macro-dashboard was priced by hand and the way a bundle is expected
// to be priced. Before this, 66 of 68 revenue-bearing packs sat ABOVE their
// parts (worst 30x), and pack pages lead with the bundle price beside the
// steps, so a buyer could see it.
//
//   price = ceil_to_$0.001( sum(price of each toolSlug) * (1 - PACK_DISCOUNT) ), min $0.001
//
// The table in src/skills.js (PACK_PRICES) is GENERATED from this rule against
// the live catalog and CHECKED in CI: default mode reads TARGET_URL's
// /api/pricing, recomputes every pack, and exits 1 on any drift, so a tool
// repriced later cannot leave a pack priced by a stale sum. `--write` rewrites
// the table. Counting: each advertised tool once (a step that walks
// candidates still buys one answer; the extra attempts are our cost).
//
//   TARGET_URL=http://127.0.0.1:PORT node scripts/pack-prices.js [--write] [--quiet]
import { readFileSync, writeFileSync } from "node:fs";
import { SKILL_PACKS, PACK_PRICES } from "../src/skills.js";

export const PACK_DISCOUNT = 0.10;
export const PACK_FLOOR_USD = 0.001;

export const priceUsdOf = (p) => { const n = Number(String(p ?? "").replace(/[^0-9.]/g, "")); return Number.isFinite(n) ? n : 0; };
export const ceilMilli = (usd) => Math.ceil(usd * 1000 - 1e-9) / 1000;
export const milli = (usd) => Math.round(Number(usd) * 1000); // compare prices as integers, never floats

/** The rule, pure. `priceOf(slug)` -> USD number (0 for unknown). */
export function derivedPackPrice(pack, priceOf, { discount = PACK_DISCOUNT, floor = PACK_FLOOR_USD } = {}) {
  const slugs = [...new Set(pack.toolSlugs || [])];
  const parts = slugs.reduce((a, s) => a + priceUsdOf(priceOf(s)), 0);
  return Math.max(floor, ceilMilli(parts * (1 - discount)));
}

const fmt = (n) => n.toFixed(3).replace(/0+$/, "").replace(/\.$/, ""); // whole milli-dollars, never rounded away

async function main() {
  const TARGET = (process.env.TARGET_URL || "").replace(/\/$/, "");
  if (!TARGET) { console.error("TARGET_URL required (a booted server; /api/pricing carries every tool's price)"); process.exit(2); }
  const write = process.argv.includes("--write");
  const quiet = process.argv.includes("--quiet");
  const pricing = await (await fetch(`${TARGET}/api/pricing`)).json();
  const tools = new Map((pricing.tools || pricing.endpoints || []).map((t) => [t.slug, t.price]));
  const priceOf = (slug) => tools.get(slug);
  const rows = [];
  let drift = 0, unknown = 0;
  for (const p of SKILL_PACKS) {
    const missing = (p.toolSlugs || []).filter((s) => !tools.has(s));
    if (missing.length) { unknown++; console.error(`${p.slug}: advertised tool(s) not in the catalog: ${missing.join(", ")}`); }
    const want = derivedPackPrice(p, priceOf);
    const have = PACK_PRICES[p.slug];
    const parts = [...new Set(p.toolSlugs || [])].reduce((a, s) => a + priceUsdOf(priceOf(s)), 0);
    if (have === undefined || Math.abs(have - want) > 1e-9) drift++;
    rows.push({ slug: p.slug, have, want, parts, tools: [...new Set(p.toolSlugs || [])].length });
  }
  if (!quiet) {
    for (const r of rows) if (r.have === undefined || Math.abs(r.have - r.want) > 1e-9) console.log(`${r.slug.padEnd(26)} parts $${fmt(r.parts).padEnd(7)} ${String(r.have === undefined ? "-" : "$" + fmt(r.have)).padEnd(8)} -> $${fmt(r.want)}`);
    const min = Math.min(...rows.map((r) => r.want)), max = Math.max(...rows.map((r) => r.want));
    console.log(`\n${rows.length} packs, ${drift} off the rule, ${unknown} with an unknown tool; derived range $${fmt(min)} to $${fmt(max)}`);
  }
  if (unknown) process.exit(1);
  if (write) {
    const src = readFileSync(new URL("../src/skills.js", import.meta.url), "utf8");
    const start = src.indexOf("export const PACK_PRICES = {");
    const end = src.indexOf("\n};", start) + 3;
    if (start < 0 || end < 3) { console.error("PACK_PRICES table not found in src/skills.js"); process.exit(2); }
    const body = rows.map((r) => `  ${JSON.stringify(r.slug)}: ${fmt(r.want)}, // ${r.tools} tools, parts $${fmt(r.parts)}`).join("\n");
    const table = `export const PACK_PRICES = {\n  // GENERATED by scripts/pack-prices.js --write from the live catalog: sum of the\n  // advertised tools' prices minus the ${Math.round(PACK_DISCOUNT * 100)}% bundle discount, rounded up to $0.001,\n  // never below $0.001. CI recomputes it (pack-prices.js in check mode) and fails\n  // on drift, so do not hand-edit a number here - reprice the tool, then --write.\n${body}\n};`;
    writeFileSync(new URL("../src/skills.js", import.meta.url), src.slice(0, start) + table + src.slice(end));
    console.log(`wrote ${rows.length} pack prices to src/skills.js`);
    process.exit(0);
  }
  if (drift) { console.error(`\nFAIL: ${drift} pack price(s) off the rule. Run: TARGET_URL=... node scripts/pack-prices.js --write`); process.exit(1); }
  console.log("OK: every pack price follows the rule");
}
if (import.meta.url === `file://${process.argv[1]}` || process.argv[1]?.endsWith("pack-prices.js")) main().catch((e) => { console.error(e); process.exit(2); });
